environment_version: 1
credentials:
- type: general
  id: 5OnLwdFdcxAqb1
  description: AIND Kachery Zone
  value: KACHERY_ZONE
- type: general
  id: QY5d3khtYUGlri
  description: AIND Kachery Client ID
  value: KACHERY_CLOUD_CLIENT_ID
- type: general
  id: VNLgdd0eUexw5D
  description: AIND Kachery Key
  value: KACHERY_CLOUD_PRIVATE_KEY
