#!/usr/bin/env bash
set -e

pip uninstall -y traitlets
pip install --no-cache-dir --ignore-installed traitlets==5.9.0

pip uninstall -y scikit-learn
pip install --no-cache-dir --ignore-installed scikit-learn==1.3.2