#!/usr/bin/env bash
set -e

git clone https://github.com/SpikeInterface/spikeinterface.git
cd spikeinterface
git checkout ecaf9931a33fbb316939a61604b342a1fdb0eca6
pip install .[full]
cd ..

pip uninstall -y scikit-learn
pip install --no-cache-dir --ignore-installed scikit-learn==1.3.2